# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress=zstd" "discard=async" "autodefrag" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "discard=async" "autodefrag" "noatime" ];
    };

  fileSystems."/var" =
    { device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=var" "compress=zstd" "discard=async" "autodefrag" "noatime" ];
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
